feat: visit_store
Johngtka/Biomagnthick-app pull request #28
Opened 2023-04-01 16:30 UTC by Johngtka

2023-04-04 19:22 UTC, Johngtka commented
S&M commit message proposal: 
`feat: add visit table for select patient and search (#28)`

2023-04-05 09:48 UTC, macrog requested changes
Just a few changes

2023-04-05 09:48 UTC, macrog commented on src/app/app.module.ts
> +import { MatSortModule } from '@angular/material/sort';
not needed

2023-04-05 09:48 UTC, macrog commented on src/app/services/store.service.ts
> +import { enviroment } from 'src/environments/environment.dev';
change import path to relative, the same as the above, starting with ../ do not absolute path

2023-04-05 09:48 UTC, macrog commented on src/app/visit/visit.component.ts
> +        private snacService: SnackService,
snac? what is snac? 😄 correct spelling and istall Code Spell Checker extensions

2023-04-05 09:48 UTC, macrog commented on src/app/visit/visit.component.ts
> +                (this.store = data.sort((a, b) => a.id - b.id))
`(this.store = data),` remove this part, you are assigning it the value with sort to store in a line below

2023-04-05 09:48 UTC, macrog commented on src/assets/i18n/pl.json
> +        "PATIENT_VISIT_CREATE_PATIENT": "Wystąpił błąd podczas tworzenia wizyty dla pacjenta, spróbuj ponownie później"
missing translations in English and Spanish

2023-04-06 15:38 UTC, macrog approved these changes
good work ❗

2023-04-06 15:50 UTC, merged